@extends:
  '@parent'

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.abstract:
              ordering@: 1
              type: textarea
              style: vertical
              placeholder: |
                Chapô de l'article ou de la page, affiché sur la page d'accueil ou sur les listes. Peut contenir du Markdown.
                Le chapô ne sera pas réécrit sur l'article lui-même. Si vide, un résumé sera automatiquement généré.
              rows: 2
            attribution_spacer:
              type: spacer
              text: <br /><br />
            metadata_columns:
              type: columns
              fields:
                banner_column:
                  type: column
                  fields:
                    attributions:
                      type: section
                      title: Bandeau de l'article
                      underline: true
                      fields:
                        header.header_image.image:
                          type: filepicker
                          folder: '@self'
                          preview_images: true
                          label: Image à utiliser comme bandeau
                          help: Téléversez une image ci-dessus, puis sélectionnez-là ci-contre pour l'utiliser comme bandeau.
                        header.header_image.title:
                          type: text
                          label: Titre de l'image du bandeau
                          help: Le titre de l'image utilisée pour le bandeau de la page, affiché au survol.
                        header.header_image.author:
                          type: text
                          label: Auteur de l'image du bandeau
                          help: L'auteur de l'image utilisée pour le bandeau de la page, ou équivalent appliquable affiché au survol.
                        header.header_image.link:
                          type: text
                          label: Lien vers la source de l'image du bandeau
                          help: Un lien vers la source de l'image du bandeau, s'il fait sens ; si défini, la source sera cliquable.
                          placeholder: https://…
                        header.header_image.vertical_centering:
                          type: range
                          label: Centrage vertical de l'image
                          help: |
                            Le bandeau est affiché partiellement au dessus du titre, en choisissant une bande de 380px de large, par défaut centrée.
                            Cette option vous permet de décaler vers le haut (curseur plus à gauche) ou le bas (plus à droite) la position verticale de cette bande.
                          default: 50
                          validate:
                            min: 0
                            max: 100
                        header_image_help:
                          type: display
                          size: long
                          label: Comment ajouter un bandeau ?
                          markdown: true
                          content: |
                            Pour ajouter un bandeau à l'article, téléversez ci-dessus l'image que vous désirez utiliser, et sélectionnez-là ci-dessus.

                            Préférez une image large sans forcément être trop haute (mais d'au moins 380px de haut). Seul un bandeau verticalement centré, de 380px de haut, sera visible _in fine_.
                authors_column:
                  type: column
                  fields:
                    authors:
                      type: section
                      title: Auteurs
                      underline: true
                      fields:
                        header.taxonomy.author:
                          type: array
                          label: Le ou les auteurs de l'article
                          value_only: true
        options:
          fields:
            publishing:
              fields:
                header.comments.show:
                  type: toggle
                  toggleable: true
                  label: Afficher les commentaires
                  help: |
                    Afficher les commentaires sur l'article ?
                    Si désactivé, les commentaires seront masqués et il ne sera plus possible de commenter.
                  highlight: 1
                  size: medium
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool
                header.comments.allow_new:
                  type: toggle
                  toggleable: true
                  label: Autoriser l'envoi de nouveaux commentaires
                  help: |
                    Permettre aux lecteurs d'envoyer de nouveaux commentaires ?
                    Si désactivé mais que l'option précédente reste activée, les commentaires resteront lisibles mais en lecture seule.
                  highlight: 1
                  size: medium
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool
            license:
              type: section
              title: Licence
              underline: true
              fields:
                header.license:
                  type: select
                  label: Licence
                  help: La licence de publication du contenu
                  default: by-sa
                  options:
                    cc0: Placement dans le domaine public (Creative Commons Zéro)
                    by: Creative Commons Attribution (CC BY 4.0)
                    by-sa: Creative Commons Attribution – Partage sous les mêmes conditions (CC BY SA 4.0)
                    by-nc: Creative Commons Attribution – Pas d'usage commercial (CC BY NC 4.0)
                    by-nd: Creative Commons Attribution – Pas de modifications (CC BY ND 4.0)
                    by-nc-nd: Creative Commons Attribution – Pas d'usage commercial – Pas de modifications (CC BY NC ND 4.0)
                    by-nc-sa: Creative Commons Attribution – Pas d'usage commercial – Partage sous les mêmes conditions (CC BY NC SA 4.0)
                    'Tous droits réservés': Tous droits réservés
                license_help:
                  type: display
                  size: long
                  label: Qu'est-ce que la licence ?
                  markdown: true
                  content: |
                    La licence du contenu précise sous quelles conditions le contenu peut être repartagé (ces conditions pouvant être combinées) :
                    - en citant l'auteur (**attribution**) ;
                    - en partageant sous la même licence, afin que le contenu reste librement partageable (**partage sous les mêmes conditions**) ;
                    - en interdisant l'usage commercial (**pas d'usage commercial**) ;
                    - en interdisant la modification (**pas de modification**) ;
                    - en interdisant tout usage, y compris de reproduction (**tous droits réservés**) ;
                    - ou en plaçant le contenu dans le domaine public, renonçant alors à l'intégralité de ses droits dessus.
